# Generated by Django 4.1 on 2022-08-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_rep',
            field=models.URLField(default='https://www.google.com'),
        ),
        migrations.AddField(
            model_name='project',
            name='nombre',
            field=models.CharField(default='temporal', max_length=100),
        ),
    ]
