# Generated by Django 4.1 on 2022-08-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_git_rep_project_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(default='https://github.com/DSavinon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_rep',
            field=models.URLField(default='https://github.com/DSavinon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
